# Generated by Django 5.2 on 2025-04-09 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('ingredients', models.TextField(verbose_name='ingredients')),
                ('preparation', models.TextField(verbose_name='preparation method')),
                ('featured_image', models.ImageField(upload_to='food_images/', verbose_name='featured image')),
                ('cultural_significance', models.TextField(blank=True, null=True, verbose_name='cultural significance')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='is vegetarian')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'food item',
                'verbose_name_plural': 'food items',
            },
        ),
        migrations.CreateModel(
            name='LifestyleElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('featured_image', models.ImageField(upload_to='lifestyle_images/', verbose_name='featured image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'lifestyle element',
                'verbose_name_plural': 'lifestyle elements',
            },
        ),
        migrations.CreateModel(
            name='OkBajiStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='year')),
                ('story', models.TextField(verbose_name='story')),
                ('impact', models.TextField(blank=True, null=True, verbose_name='impact')),
                ('featured_image', models.ImageField(upload_to='okbaji_images/', verbose_name='featured image')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'OK Baji story',
                'verbose_name_plural': 'OK Baji stories',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('message', models.TextField(verbose_name='message')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
            },
        ),
        migrations.CreateModel(
            name='CulturalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('featured_image', models.ImageField(upload_to='cultural_images/', verbose_name='featured image')),
                ('importance', models.TextField(blank=True, null=True, verbose_name='importance')),
                ('season', models.CharField(blank=True, max_length=100, null=True, verbose_name='season')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='video URL')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultural_events', to='village.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'cultural event',
                'verbose_name_plural': 'cultural events',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='image')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='location')),
                ('date_taken', models.DateField(blank=True, null=True, verbose_name='date taken')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='village.category', verbose_name='category')),
            ],
            options={
                'verbose_name': 'gallery item',
                'verbose_name_plural': 'gallery items',
            },
        ),
    ]
