# Generated by Django 5.2 on 2025-09-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='section',
            field=models.CharField(choices=[('cultural', 'Cultural Events'), ('food', 'Food Items'), ('lifestyle', 'Lifestyle'), ('gallery', 'Gallery')], default='cultural', max_length=50, verbose_name='section'),
            preserve_default=False,
        ),
    ]
