# Generated by Django 5.2 on 2025-09-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0002_testimonial_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='item_id',
            field=models.PositiveIntegerField(default=0, verbose_name='item ID'),
        ),
    ]
