# Generated by Django 5.2 on 2025-09-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0003_testimonial_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='item_id',
            field=models.PositiveIntegerField(verbose_name='item ID'),
        ),
    ]
