# Generated by Django 5.2 on 2025-09-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('village', '0004_alter_testimonial_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tradition', 'Tradition'), ('event', 'Cultural Event'), ('homestay', 'Homestay'), ('gallery', 'Gallery')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='highlights/')),
                ('path', models.CharField(help_text='Frontend path to navigate', max_length=200)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
