# Generated by Django 5.2 on 2025-04-09 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(verbose_name='check-in date')),
                ('check_out_date', models.DateField(verbose_name='check-out date')),
                ('number_of_guests', models.PositiveSmallIntegerField(verbose_name='number of guests')),
                ('special_requests', models.TextField(blank=True, null=True, verbose_name='special requests')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20, verbose_name='status')),
                ('booking_date', models.DateTimeField(auto_now_add=True, verbose_name='booking date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
            },
        ),
        migrations.CreateModel(
            name='HomestayFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='family name')),
                ('head_of_family', models.CharField(max_length=100, verbose_name='head of family')),
                ('contact_number', models.CharField(max_length=15, verbose_name='contact number')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('featured_image', models.ImageField(upload_to='homestay_images/', verbose_name='featured image')),
                ('amenities', models.TextField(blank=True, null=True, verbose_name='amenities')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'homestay family',
                'verbose_name_plural': 'homestay families',
            },
        ),
        migrations.CreateModel(
            name='HomestayImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('image', models.ImageField(upload_to='homestay_images/', verbose_name='image')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('comment', models.TextField(verbose_name='comment')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'review',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='capacity')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price per night')),
                ('featured_image', models.ImageField(upload_to='room_images/', verbose_name='featured image')),
                ('amenities', models.TextField(verbose_name='amenities')),
                ('is_available', models.BooleanField(default=True, verbose_name='is available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
            },
        ),
    ]
