# Generated by Django 5.2 on 2025-04-09 05:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homestay', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='homestayfamily',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='homestay_families', to='homestay.homestayimage'),
        ),
        migrations.AddField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='homestay.booking', verbose_name='booking'),
        ),
        migrations.AddField(
            model_name='review',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='homestay.homestayfamily', verbose_name='homestay'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='room',
            name='gallery_images',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='homestay.homestayimage'),
        ),
        migrations.AddField(
            model_name='room',
            name='homestay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homestay.homestayfamily', verbose_name='homestay'),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='homestay.room', verbose_name='room'),
        ),
    ]
